import { useEffect, useState } from "react";

const categories = [
  { id: "student", name: "Student", format: "Learning portfolio", intro: "Showcase learning, potential, and projects." },
  { id: "professional", name: "Professional", format: "Professional portfolio", intro: "Lead with expertise, impact, and craft." },
  { id: "employee", name: "Fresher", format: "Career portfolio", intro: "Present your potential, projects, and career direction." },
];
const defaults = { category: "student", name: "Alex Morgan", role: "Product designer & creative developer", location: "Based in London, working worldwide", bio: "I turn complex ideas into clear, useful digital experiences. Currently crafting thoughtful products at the intersection of design and technology.", email: "alex@morgan.design", website: "alexmorgan.design", phone: "", linkedin: "", github: "", photo: "", degree: "", university: "", graduationYear: "", gpa: "", skills: "", achievements: "", headline: "", objective: "", preferredRole: "", industry: "", workMode: "", currentTitle: "", experience: "", expertise: "", specialization: "", companyName: "", jobTitle: "", employmentType: "", companyLocation: "", keyAchievements: "", technologies: "", projectsWorkedOn: "", featuredProject: "Lumen Finance", projectDescription: "A calmer way for people to understand and grow their money." };
const templates = [{ id: "editorial", name: "Editorial", detail: "Bold type, generous rhythm", color: "#f2ede4" }, { id: "studio", name: "Studio", detail: "Quiet, precise, minimal", color: "#e5edf2" }, { id: "mono", name: "Mono", detail: "Sharp contrast, full focus", color: "#e8e5df" }];

function Home() {
  const [active, setActive] = useState("overview");
  const [profile, setProfile] = useState(() => { try { return { ...defaults, ...(JSON.parse(localStorage.getItem("portfolio-profile")) || {}) }; } catch { return defaults; } });
  const [template, setTemplate] = useState("editorial");
  const [accent, setAccent] = useState("#e35d3f");
  const [published, setPublished] = useState(false);
  const category = categories.find((item) => item.id === profile.category) || categories[0];
  useEffect(() => { localStorage.setItem("portfolio-profile", JSON.stringify(profile)); }, [profile]);
  const navigate = (module) => setActive(module);
  const update = (event) => setProfile({ ...profile, [event.target.name]: event.target.value });
  const chooseCategory = (id) => setProfile({ ...profile, category: id });
  const exportPortfolio = () => { const blob = new Blob([JSON.stringify({ profile, template, accent }, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "portfolio.json"; link.click(); URL.revokeObjectURL(link.href); };
  const modules = [["overview", "Overview", "⌂"], ["profile", "Profile", "○"], ["portfolio", "Portfolio", "▧"], ["templates", "Templates", "✦"], ["preview", "Live preview", "◉"], ["admin", "Admin", "⚙"]];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">/</span><span>folio<span className="brand-dot">.</span>craft</span></div><div className="workspace-label">WORKSPACE <span>personal</span></div><nav>{modules.map(([id, label, icon]) => <button key={id} className={active === id ? "nav-item active" : "nav-item"} onClick={() => navigate(id)}><span className="nav-icon">{icon}</span>{label}{id === "preview" && <span className="live-dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="plan"><span>FREE PLAN</span><strong>1 of 3 portfolios</strong><div className="progress"><i /></div><button onClick={() => navigate("admin")}>Manage plan <span>→</span></button></div><div className="user-row"><div className="avatar">AM</div><div><strong>{profile.name}</strong><small>{category.name} portfolio</small></div></div></div></aside><main className="main-area"><header className="topbar"><div className="breadcrumb">MY PORTFOLIO <span>/</span> <strong>{active === "overview" ? "DASHBOARD" : active.toUpperCase()}</strong></div><div className="top-actions"><span className={published ? "status published" : "status"}><i />{published ? "Published" : "Draft saved"}</span><button className="help-button">?</button></div></header><section className="content">{active === "overview" && <Overview profile={profile} category={category} chooseCategory={chooseCategory} navigate={navigate} published={published} />}{active === "profile" && <Editor portfolio={false} category={category} profile={profile} update={update} navigate={navigate} />}{active === "portfolio" && <Editor portfolio category={category} profile={profile} update={update} navigate={navigate} />}{active === "templates" && <Templates category={category} template={template} setTemplate={setTemplate} accent={accent} setAccent={setAccent} />}{active === "preview" && <Preview profile={profile} category={category} template={template} accent={accent} />}{active === "admin" && <Admin published={published} setPublished={setPublished} exportPortfolio={exportPortfolio} />}</section></main></div>;
}

function CategoryPicker({ category, chooseCategory }) { return <div className="category-picker"><div><span className="eyebrow">START HERE / PORTFOLIO TYPE</span><h2>What describes you best?</h2><p>Your category shapes the structure and language of your portfolio.</p></div><div className="category-options">{categories.map((item) => <button className={category.id === item.id ? "category-option selected" : "category-option"} key={item.id} onClick={() => chooseCategory(item.id)}><span className="category-number">0{categories.indexOf(item) + 1}</span><span><strong>{item.name}</strong><small>{item.intro}</small></span>{category.id === item.id && <b>✓</b>}</button>)}</div></div>; }
function Overview({ profile, category, chooseCategory, navigate, published }) { return <><div className="page-heading"><div><p className="eyebrow">GOOD MORNING, {profile.name.split(" ")[0].toUpperCase()}</p><h1>Your {category.name.toLowerCase()} portfolio,<br /><em>in progress.</em></h1></div><button className="primary-button" onClick={() => navigate("preview")}>View live site <span>↗</span></button></div><CategoryPicker category={category} chooseCategory={chooseCategory} /><div className="overview-grid"><div className="build-card"><div className="card-top"><div><span className="eyebrow">{category.format.toUpperCase()}</span><h2>Make your work<br />speak for itself.</h2></div><div className="completion">68<small>%</small></div></div><div className="meter"><i /></div><div className="completion-row"><span>4 of 6 sections complete</span><span>Keep going <b>→</b></span></div><div className="steps"><button onClick={() => navigate("profile")}><span className="step-number done">✓</span><span><b>Set up your {category.name.toLowerCase()} profile</b><small>Identity and introduction</small></span><strong>Done</strong></button><button onClick={() => navigate("portfolio")}><span className="step-number done">✓</span><span><b>Add your best work</b><small>{category.id === "student" ? "Projects and coursework" : category.id === "employee" ? "Experience and results" : "Projects and case studies"}</small></span><strong>Done</strong></button><button onClick={() => navigate("templates")}><span className="step-number current">3</span><span><b>Choose your look</b><small>Category-ready visual style</small></span><strong>Start</strong></button></div></div><div className="quick-card"><span className="eyebrow">QUICK ACTIONS</span><h3>Shape the story.</h3><button onClick={() => navigate("profile")}>✎ &nbsp; Edit profile <b>→</b></button><button onClick={() => navigate("portfolio")}>＋ &nbsp; Add a project <b>→</b></button><button onClick={() => navigate("templates")}>✦ &nbsp; Change template <b>→</b></button></div></div><div className="lower-row"><div><span className="eyebrow">YOUR SITE</span><h3>{published ? "Your portfolio is live." : "A thoughtful first draft."}</h3><p>{category.format} <span>•</span> {published ? "Public link active" : "Only you can see this"}</p></div><button className="secondary-button" onClick={() => navigate("admin")}>{published ? "Manage site" : "Publish portfolio"} <span>↗</span></button></div></>; }
const personalFields = [
  ["name", "Full name"], ["photo", "Profile photo (optional)"], ["email", "Email"], ["phone", "Phone"],
  ["location", "Location"], ["linkedin", "LinkedIn"], ["github", "GitHub"], ["website", "Personal website (optional)"],
];
const educationFields = [["university", "College / university name"], ["degree", "Degree"], ["graduationYear", "Expected graduation / graduation year"], ["gpa", "GPA / CGPA (optional)"], ["skills", "Skills"], ["achievements", "Achievements (optional)"]];
const fresherProfessionalFields = [["headline", "Professional headline"], ["objective", "Career objective"], ["preferredRole", "Preferred job role"], ["industry", "Preferred industry"], ["workMode", "Work preference: remote / on-site / hybrid"]];
const professionalFields = [["currentTitle", "Current job title"], ["headline", "Professional headline"], ["experience", "Years of experience"], ["bio", "Professional summary"], ["expertise", "Areas of expertise"], ["specialization", "Career specialization"]];
const companyFields = [["companyName", "Company name"], ["jobTitle", "Job title"], ["employmentType", "Employment type"], ["companyLocation", "Location"], ["keyAchievements", "Key achievements"], ["technologies", "Technologies / tools used"], ["projectsWorkedOn", "Projects worked on"]];

function FormField({ field, profile, update }) {
  const [name, label] = field;
  const multiline = ["objective", "bio", "achievements", "keyAchievements", "technologies", "projectsWorkedOn", "skills", "expertise"].includes(name);
  return <label>{label}{multiline ? <textarea name={name} value={profile[name]} onChange={update} rows="3" /> : <input name={name} value={profile[name]} onChange={update} />}</label>;
}

function FormSection({ title, fields, profile, update }) {
  return <section className="form-section"><h2>{title}</h2><div className="field-grid">{fields.map((field) => <FormField key={field[0]} field={field} profile={profile} update={update} />)}</div></section>;
}

function Editor({ profile, update, portfolio, category, navigate }) {
  const sections = portfolio
    ? category.id === "professional" ? [["Company experience", companyFields]] : [["Featured work", [["featuredProject", category.id === "student" ? "Project / coursework title" : "Project title"]]], ["Description", [["projectDescription", category.id === "student" ? "What you learned or built" : "Project description"]]]]
    : category.id === "student" ? [["Personal details", personalFields], ["Education", educationFields]]
      : category.id === "employee" ? [["Personal information", personalFields], ["Professional profile", fresherProfessionalFields], ["Education", educationFields]]
        : [["Personal information", personalFields], ["Professional profile", professionalFields]];
  return <><div className="page-heading compact"><div><p className="eyebrow">{portfolio ? "02 / YOUR WORK" : "01 / FOUNDATION"}</p><h1>{portfolio ? `${category.name} portfolio content` : `${category.name} profile`}</h1><p>{category.intro}</p></div><button className="primary-button" onClick={() => navigate("preview")}>Preview <span>↗</span></button></div><div className="form-layout"><div className="form-panel">{sections.map(([title, fields]) => <FormSection key={title} title={title} fields={fields} profile={profile} update={update} />)}</div><div className="side-note"><span className="note-icon">✦</span><h3>Built for {category.name.toLowerCase()}s.</h3><p>{category.intro} The fields and portfolio format will stay aligned to this choice.</p><button onClick={() => navigate("preview")}>See the preview →</button></div></div></>;
}
function Templates({ category, template, setTemplate, accent, setAccent }) { return <><div className="page-heading compact"><div><p className="eyebrow">03 / ART DIRECTION</p><h1>Choose your look</h1><p>{category.format} format with a visual system that gives your work room to breathe.</p></div></div><div className="template-layout"><div className="template-list">{templates.map((item) => <button key={item.id} className={template === item.id ? "template-choice selected" : "template-choice"} onClick={() => setTemplate(item.id)}><span className="template-thumb" style={{ background: item.color }}><i /><b /><em /></span><span><strong>{item.name}</strong><small>{item.detail}</small></span>{template === item.id && <span className="check">✓</span>}</button>)}<div className="color-setting"><span className="eyebrow">ACCENT COLOR</span><div className="swatches">{["#e35d3f", "#287c72", "#3156a3", "#d19a27", "#252525"].map((color) => <button key={color} aria-label={color} className={accent === color ? "swatch chosen" : "swatch"} style={{ background: color }} onClick={() => setAccent(color)} />)}</div></div></div><div className={`template-preview ${template}`} style={{ "--accent": accent }}><span className="preview-label">{category.format.toUpperCase()}</span><div><p>AM</p><h2>{category.name} / {profileWord(category)}</h2><strong>{category.id === "student" ? "Curious learner & maker" : category.id === "employee" ? "Results-driven team member" : "Product designer & creative developer"}</strong><div className="preview-line" /></div></div></div></>; }
function profileWord(category) { return category.id === "student" ? "PORTFOLIO" : category.id === "employee" ? "CAREER" : "WORK"; }
function Preview({ profile, category, accent }) { return <div className="preview-page"><div className="page-heading compact"><div><p className="eyebrow">LIVE PREVIEW / {category.format.toUpperCase()}</p><h1>See it in the wild.</h1><p>This is exactly what your visitors will see.</p></div><button className="secondary-button" onClick={() => window.print()}>Print / PDF <span>↓</span></button></div><div className="portfolio-preview" style={{ "--accent": accent }}><span className="preview-nav">{profile.name} <span>About&nbsp;&nbsp;&nbsp; {category.id === "student" ? "Projects" : category.id === "employee" ? "Experience" : "Work"}&nbsp;&nbsp;&nbsp; Contact</span></span><div className="portfolio-hero"><p className="eyebrow">{category.id === "student" ? "HELLO, I'M A LEARNER" : category.id === "employee" ? "HELLO, I'M A PROFESSIONAL" : "HELLO, I'M A CREATIVE"}</p><h2>{profile.role}</h2><p>{profile.bio}</p><a href={`mailto:${profile.email}`}>Let's work together <span>↗</span></a></div><div className="project-feature"><span className="eyebrow">{category.id === "employee" ? "CAREER HIGHLIGHT / 01" : category.id === "student" ? "SELECTED PROJECT / 01" : "SELECTED WORK / 01"}</span><h3>{profile.featuredProject}</h3><p>{profile.projectDescription}</p></div></div></div>; }
function Admin({ published, setPublished, exportPortfolio }) { return <><div className="page-heading compact"><div><p className="eyebrow">CONTROL ROOM</p><h1>Admin management</h1><p>Manage visibility, exports, and your public portfolio.</p></div><button className="primary-button" onClick={() => setPublished(!published)}>{published ? "Unpublish site" : "Publish site"} <span>↗</span></button></div><div className="admin-grid"><div className="admin-status"><span className={published ? "big-status live" : "big-status"}><i />{published ? "LIVE" : "DRAFT"}</span><h2>{published ? "Your portfolio is out in the world." : "Your portfolio is ready when you are."}</h2><p>{published ? "Anyone with your public link can view your work." : "Review your live preview, then publish when it feels right."}</p><div className="public-link">foliocraft.me/alex-morgan<button onClick={() => navigator.clipboard?.writeText("foliocraft.me/alex-morgan")}>Copy link</button></div></div><div className="admin-actions"><span className="eyebrow">PORTFOLIO TOOLS</span><button onClick={exportPortfolio}>↓ <div><strong>Export data</strong><small>Download a JSON backup</small></div><b>→</b></button><button onClick={() => setPublished(true)}>↗ <div><strong>Share portfolio</strong><small>Make your public link active</small></div><b>→</b></button></div></div></>; }
export default Home;